source/repos/Das_Des_2/Das_Des_2/Models/GenderViewModel/GenderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Das_Des_2.Models.GenderViewModel
{
    public class GenderViewModel
    {
        [Required]
        [Display(Name ="Genero")]
        public string nameGender { get; set; }
    }
}

source/repos/Das_Des_2/Das_Des_2/Models/Peli/Gender.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Das_Des_2.Models.Peli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gender()
        {
            this.Movie = new HashSet<Movie>();
        }
    
        public int idGender { get; set; }
        public string nameGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Movie { get; set; }
    }
}

source/repos/Das_Des_2/Das_Des_2/Controllers/GenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Das_Des_2.Models.Peli;
using Das_Des_2.Models.GenderViewModel;

namespace Das_Des_2.Controllers
{
    public class GenderController : Controller
    {
        // GET: Gender
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create ()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(GenderViewModel model)
        {
            using (var db = new CinePlusEntities())
            {
                Gender oGender = new Gender();

                oGender.idGender = 1;
                oGender.nameGender = model.nameGender;

                db.Gender.Add(oGender);
                db.SaveChanges();
                
            }
            return Redirect("Index");
        }
    }
}

source/repos/Das_Des_2/Das_Des_2/Views/Gender/Create.cshtml
@model Das_Des_2.Models.GenderViewModel.GenderViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Create", "Gender", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            @Html.LabelFor(d => d.nameGender)
            @Html.TextBoxFor(d => d.nameGender, new { @class = "form-control form-control-lg" })
            @Html.ValidationMessage("nameGeder", new { @class = "text-danger" })
            <br />

            <div>
                <input type="submit" class="btn btn-success  btn-lg" value="Guardar" />
            </div>
        }
    </div>
</div>

source/repos/Das_Des_2/Das_Des_2/Views/Gender/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>