source/repos/Das_Des_2/Das_Des_2/Models/PeliculaViewModel/PeliculaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Das_Des_2.Models.PeliculaViewModel
{
    public class PeliculaViewModel
    {
        [Required]
        [Display(Name = "Nombre de Película")]
        public string NameMovie { get; set; }
        [Required]
        [Display(Name = "Descipción de Película")]
        public string DescriptionMovie { get; set; }
        
        [Required]
        [Display(Name = "Director de Película")]
        public string DirectorMovie { get; set; }
        [Required]
        [Display(Name = "Imagen de Película")]
        public HttpPostedFileBase File {get; set; }
        public List<SelectListItem> GenderMovie { get; set; }
    }
    public class EditPeliculaViewModel
    {
        public int IdMovie { get; set; }
        
        [Display(Name = "Nombre de Película")]
        public string NameMovie { get; set; }
        
        [Display(Name = "Descipción de Película")]
        public string DescriptionMovie { get; set; }

        [Display(Name = "Director de Película")]
        public string DirectorMovie { get; set; }
        
        [Display(Name = "Imagen de Película")]
        public HttpPostedFileBase File { get; set; }
        public List<SelectListItem> GenderMovie { get; set; }

        public string ImageUrl { get; set; }
    }
}

source/repos/Das_Des_2/Das_Des_2/Controllers/PeliculaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Das_Des_2.Models.PeliculaViewModel;
using Das_Des_2.Models.Peli;
using Das_Des_2.Models.PeliculaTableViewModel;
using PagedList;

namespace Das_Des_2.Controllers
{
    public class PeliculaController : Controller
    {

        // GET: Pelicula
        public ActionResult Index()
        {
            if(TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
            }
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            List<SelectListItem> lstGender = new List<SelectListItem>();

            using (var db = new CinePlusEntities())
            {
                lstGender = (from d in db.Gender
                             select new SelectListItem
                             {
                                 Value = d.idGender.ToString(),
                                 Text = d.nameGender
                             }).ToList();
            }

            ViewBag.GenderList = lstGender;            
            return View();
        }
        [HttpPost]
        public ActionResult Create(PeliculaViewModel model, string GenderList)
        {
            var RutaSitio = Server.MapPath("~/");
            var NameFile = System.IO.Path.Combine(RutaSitio + "/upluad/" + model.File.FileName);
            var FileName = System.IO.Path.Combine("/upluad/" + model.File.FileName);

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            model.File.SaveAs(NameFile);

            using(var db = new CinePlusEntities())
            {
                Movie oMmovie = new Movie();
                oMmovie.idMovie = 1;
                oMmovie.nameMovie = model.NameMovie;
                oMmovie.descriptionMovie = model.DescriptionMovie;
                oMmovie.genderMovie = int.Parse(GenderList);
                oMmovie.directorMovie = model.DirectorMovie;
                oMmovie.imgMovie = FileName.ToString();
                db.Movie.Add(oMmovie);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ShowPelicula(int? pageSize, int? page)
        {
            List<PeliculaTableViewModel> lst = new List<PeliculaTableViewModel>();
            List<SelectListItem> VoteList = new List<SelectListItem>();
            VoteList.Add(new SelectListItem() { Text = "1", Value = "1" });
            VoteList.Add(new SelectListItem() { Text = "2", Value = "2" });
            VoteList.Add(new SelectListItem() { Text = "3", Value = "3" });
            VoteList.Add(new SelectListItem() { Text = "4", Value = "4" });
            VoteList.Add(new SelectListItem() { Text = "5", Value = "5" });

            using (var db = new CinePlusEntities())
            {
                lst = (from d in db.Movie
                       join b in db.Gender
                       on d.genderMovie equals b.idGender
                       select new PeliculaTableViewModel
                       {
                           IdMovie = d.idMovie,
                           NameMovie = d.nameMovie,
                           DescriptionMovie = d.descriptionMovie,
                           DirectorMovie = d.directorMovie,
                           ImgMovie = d.imgMovie,
                           GeneroMovie = b.nameGender
                       }).ToList(); 
            }

            pageSize = (pageSize ?? 5);
            page = (page ?? 1);

            ViewBag.Vote = VoteList;
            ViewBag.PageSize = pageSize;
            return View(lst.ToPagedList(page.Value, pageSize.Value));
        }

        [HttpPost]
        public ActionResult AddVote(string Vote, string Id)
        {
            using (var db = new CinePlusEntities())
            {
                Vote oVote = new Vote();
                oVote.idVoto = 1;
                oVote.valueVoto = int.Parse(Vote);
                oVote.idMovie = int.Parse(Id);

                db.Vote.Add(oVote);
                db.SaveChanges();
            }
            return RedirectToAction("ShowPelicula");
        }

        [HttpGet]
        public ActionResult ShowTablePelicula ()
        {
            List<PeliculaTableViewModel> lst = new List<PeliculaTableViewModel>();
            using (var db = new CinePlusEntities())
            {
                lst = (from d in db.Movie
                       join b in db.Gender
                       on d.genderMovie equals b.idGender
                       select new PeliculaTableViewModel
                       {
                           IdMovie = d.idMovie,
                           NameMovie = d.nameMovie,
                           DescriptionMovie = d.descriptionMovie,
                           DirectorMovie = d.directorMovie,
                           ImgMovie = d.imgMovie,
                           GeneroMovie = b.nameGender
                       }).ToList();
            }
            return View(lst);
        }
        [HttpPost]
        public ActionResult Delete(int Id)
        {
            using (var db = new CinePlusEntities())
            {
                var oMovie = db.Movie.Find(Id);
                db.Movie.Remove(oMovie);
                db.SaveChanges();
            }
            return Content("1");
        }
        public ActionResult Edit(int Id)
        {
            List<SelectListItem> lstGender = new List<SelectListItem>();
            EditPeliculaViewModel model = new EditPeliculaViewModel();

            using (var db = new CinePlusEntities())
            {
                lstGender = (from d in db.Gender
                             select new SelectListItem
                             {
                                 Value = d.idGender.ToString(),
                                 Text = d.nameGender
                             }).ToList();

                var oMovie = db.Movie.Find(Id);
                model.IdMovie = oMovie.idMovie;
                model.NameMovie = oMovie.nameMovie;
                model.DescriptionMovie = oMovie.descriptionMovie;
                model.DirectorMovie = oMovie.directorMovie;
                model.ImageUrl = oMovie.imgMovie;
            }
            ViewBag.GenderList = lstGender;

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditPeliculaViewModel model, string GenderList)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new CinePlusEntities())
            {
                var oMovie = db.Movie.Find(model.IdMovie);
                oMovie.nameMovie = model.NameMovie;
                oMovie.descriptionMovie = model.DescriptionMovie;
                oMovie.directorMovie = model.DirectorMovie;
                oMovie.genderMovie = int.Parse(GenderList);

                if (model.File != null)
                {
                    var RutaSitio = Server.MapPath("~/");
                    var NameFile = System.IO.Path.Combine(RutaSitio + "/upluad/" + model.File.FileName);
                    var FileName = System.IO.Path.Combine("/upluad/" + model.File.FileName);
                    oMovie.imgMovie = FileName; 

                    model.File.SaveAs(NameFile);

                }
                oMovie.imgMovie = model.ImageUrl;

                db.Entry(oMovie).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

            }
            return Redirect(Url.Content("~/User/ShowUser"));
        }
    }
}

source/repos/Das_Des_2/Das_Des_2/Views/Pelicula/Create.cshtml
@model Das_Des_2.Models.PeliculaViewModel.PeliculaViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Pelicula", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(d => d.NameMovie)
            @Html.TextBoxFor(d => d.NameMovie, new { @class = "form-control form-control-lg" })
            @Html.ValidationMessage("NameMovie", new { @class = "text-danger" })
            <br />

            @Html.LabelFor(d => d.DescriptionMovie)
            @Html.TextBoxFor(d => d.DescriptionMovie, new { @class = "form-control form-control-lg" })
            @Html.ValidationMessage("DescriptionMovie", new { @class = "text-danger" })
            <br />
            @Html.Label("Genero")
            @Html.DropDownList("GenderList", null, new { @class = "form-control form-control-lg" })
            <br />

            @Html.LabelFor(d => d.DirectorMovie)
            @Html.TextBoxFor(d => d.DirectorMovie, new { @class = "form-control form-control-lg" })
            @Html.ValidationMessage("DirectorMovie", new { @class = "text-danger" })
            <br />
            <div class="form-group">
                @Html.LabelFor(d => d.File)
                @Html.TextBoxFor(d => d.File, new { type = "file", accept = "image/*", @class = "form-control form-control-lg" })
                @Html.ValidationMessage("DescriptionMovie", new { @class = "text-danger" })
            </div>
            <br />
            <div>
                <input type="submit" class="btn btn-success  btn-lg" value="Guardar" />
            </div>
        </div>
    </div>

}

source/repos/Das_Des_2/Das_Des_2/Views/Pelicula/Edit.cshtml
@model Das_Des_2.Models.PeliculaViewModel.EditPeliculaViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Editar</h2>

@using (Html.BeginForm("Edit", "Pelicula", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.ImageUrl)
            @Html.HiddenFor(d => d.IdMovie)
            @Html.ValidationMessage("error", new { @class = "text-danger" })
            <br />
            @Html.LabelFor(d => d.NameMovie)
            @Html.TextBoxFor(d => d.NameMovie, new { @class = "form-control form-control-lg" })
            @Html.ValidationMessage("NameMovie", new { @class = "text-danger" })
            <br />

            @Html.LabelFor(d => d.DescriptionMovie)
            @Html.TextBoxFor(d => d.DescriptionMovie, new { @class = "form-control form-control-lg" })
            @Html.ValidationMessage("DescriptionMovie", new { @class = "text-danger" })
            <br />
            @Html.Label("Genero")
            @Html.DropDownList("GenderList", null, new { @class = "form-control form-control-lg" })
            <br />

            @Html.LabelFor(d => d.DirectorMovie)
            @Html.TextBoxFor(d => d.DirectorMovie, new { @class = "form-control form-control-lg" })
            @Html.ValidationMessage("DirectorMovie", new { @class = "text-danger" })
            <br />
            <div class="form-group">
                @Html.LabelFor(d => d.File)
                @Html.TextBoxFor(d => d.File, new { type = "file", accept = "image/*", @class = "form-control form-control-lg" })
                @Html.ValidationMessage("DescriptionMovie", new { @class = "text-danger" })
            </div>
            <br />
            <div>
                <input type="button" onclick="document.location.href='@Url.Content("~/Pelicula/ShowTablePelicula")'" class="btn btn-danger btn-lg" value="Cancenar" />
                <input type="submit" class="btn btn-success  btn-lg" value="Guardar" />
            </div>
        </div>
    </div>

}

source/repos/Das_Des_2/Das_Des_2/Views/Pelicula/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    <input type="button" onclick="document.location.href='@Url.Content("~/Pelicula/ShowTablePelicula")'" class="btn btn-danger btn-lg" value="Ver" />
</div>

<div>
    <input type="button" onclick="document.location.href='@Url.Content("~/Pelicula/Create")'" class="btn btn-danger btn-lg" value="Crear" />
</div>

source/repos/Das_Des_2/Das_Des_2/Views/Pelicula/ShowPelicula.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Das_Des_2.Models.PeliculaTableViewModel.PeliculaTableViewModel>
@{
    ViewBag.Title = "ShowPelicula";
}

<h2>ShowPelicula</h2>

<div class="container">
    <div class="row">
        <div class="d-flex justify-content-center">
            <div class="col-lg-6 col-sm-12" id="itemmenu">
                @foreach (var oModel in Model)
                {
                    <div class="card mb-6 card-border" style="max-width: 540px;">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="@oModel.ImgMovie" width="140px" height="320px" class="card-img-top" alt="@oModel.NameMovie">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h4 class="card-title">@oModel.NameMovie</h4>
                                    <p>@oModel.DescriptionMovie</p>
                                    <h5>@oModel.DirectorMovie</h5>
                                    <h5>@oModel.GeneroMovie</h5>
                                    <div>
                                        @using (Html.BeginForm("AddVote", "Pelicula", FormMethod.Post))
                                        {
                                            @Html.AntiForgeryToken()

                                            @Html.Hidden("Id", oModel.IdMovie.ToString())

                                            @Html.Label("Valorar Película")
                                            <br />
                                            @Html.DropDownList("Vote", null, new { @class = "dropdown" })
                                            <br />
                                            <div>
                                                <input type="submit" class="btn btn-success" value="Votar" />
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


<br />

@Html.PagedListPager(Model, page => Url.Action("ShowPelicula", "Pelicula", new { page, PageSize = ViewBag.pageSize }))

source/repos/Das_Des_2/Das_Des_2/Views/Pelicula/ShowTablePelicula.cshtml
@model List<Das_Des_2.Models.PeliculaTableViewModel.PeliculaTableViewModel>
@{
    ViewBag.Title = "ShowTablePelicula";
}

<h2>ShowTablePelicula</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Descripción</th>
            <th scope="col">Genero</th>
            <th scope="col">Director</th>
            <th scope="col">Imagen</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var oModel in Model)
        {
            <tr>
                <th scope="row">@oModel.NameMovie</th>
                <td>@oModel.DescriptionMovie</td>
                <td>@oModel.GeneroMovie</td>
                <td>@oModel.DirectorMovie</td>
                <th><img src="@oModel.ImgMovie" width="140px" height="320px" class="card-img-top" alt="@oModel.NameMovie"></th>
                <td><input onclick="document.location.href='@Url.Content("~/Pelicula/Edit/"+oModel.IdMovie)'" type="button" class="btn btn-primary" value="Editar" />  </td>
                <td><input onclick="funcDelete(@oModel.IdMovie)" type="button" class="btn btn-danger" value="Eliminar" /></td>
            </tr>
        }
    </tbody>
</table>

<script>
    function funcDelete(id) {
        if (confirm("Desea eliminar la Pelicula")) {
            url = "@Url.Content("~/Pelicula/Delete/")" + id;
            $.post(url, function (data) {
                if (data == "1") {
                    document.location.href = "@Url.Content("~/Pelicula/ShowTablePelicula")";
                } else {
                    alert("Error al eliminar usuario");
                }
            });
        };
    };
</script>